#!/usr/bin/env bash
# Args: $APP

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname $0)/../common/functions"

APP="$1"
IMAGE="dokku/$APP"

dokku_log_info1 "Custom Procfile plugin"

# get procfile env var
PROCFILE=$(dokku config:get $APP PROCFILE)

CMD=$(cat << EOF
cd "/app" &&
echo "$PROCFILE" > Procfile
EOF
)

dokku_log_info1 "Customizing Procfile"
id=$(docker run -d $IMAGE /bin/bash -c "$CMD")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
dokku_log_info1 "New Procfile ready"
