#!/usr/bin/env bash
# Args: $APP

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname $0)/../common/functions"

APP="$1"
IMAGE="dokku/$APP"

echo "----> $PROCFILE"

dokku_log_info1 "Customizing Procfile"
id=$(docker run -d $IMAGE /bin/bash -c "cd /app && gulp default")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
dokku_log_info1 "New Procfile ready"
